# Generated by Django 2.2 on 2019-04-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190407_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dogecoin_wallet',
            field=models.CharField(default='', max_length=34),
        ),
    ]
