# Generated by Django 2.2 on 2019-04-23 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190411_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dogecoin_wallet',
            field=models.CharField(blank=True, max_length=34, null=True, validators=[django.core.validators.RegexValidator('^(D)[^OIYWa-z][A-Za-z0-9]{32}$', message="your dogecoin wallet address should start with the letter 'D' and be a combination of letters and numbers"), django.core.validators.MinLengthValidator(34)]),
        ),
    ]
