# Generated by Django 2.2 on 2020-09-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20190423_0035")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(max_length=240, null=True),
        )
    ]
