# Generated by Django 2.2 on 2020-09-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20200920_1641")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.CharField(default="default.png", max_length=240),
        )
    ]
