version: '3'

services:
  db:
    restart: always
    image: "postgres:11.9-alpine"
    container_name: pay-me-in-doge-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=paymeindoge
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    restart: always
    build: .
    command: /bin/sh -c "code/docker-entrypoint.sh"
    container_name: pay-me-in-doge
    environment:
      - ENV=dev
    env_file: .env
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  db-data:
