# Generated by Django 2.2 on 2019-04-23 00:35

import common.util.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='url',
            field=models.CharField(max_length=50, validators=[common.util.validators.validate_url]),
        ),
    ]
